export default {
    title: 'Education',
    data: [
        {
            school: 'NYU',
            schoolFull: 'New York University',
            college: 'Graduate School of Arts and Science ',
            logo: './school/nyu.png',
            startDate: '2023-09',
            graduationDate: undefined,
            degree: 'Master of Science',
            major: 'Data Science',
        },
        {
            school: 'UCSB',
            schoolFull: 'University of California, Santa Barbara',
            college: 'College of Letters and Science',
            logo: './school/ucsb.png',
            startDate: '2019-09',
            graduationDate: '2023-06',
            degree: 'Bachelor of Science',
            major: 'Applied Mathematics',
            major2: 'Statistics and Data Science',
            major3: 'Psychological and Brain Science',
        },
        {
            school: 'hfi',
            college: 'International Department',
            schoolFull: 'Affiliated High School of South China Normal University',
            logo: './school/hfi.png',
            startDate: '2016-09',
            graduationDate: '2019-06',
        },
    ],
    status: 0,
}
